name: CI

on:
  push:
  schedule:
    - cron: "0 8 * * *"

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
    - name: Prepare env
      run: |
        python -m pip install -r ./requirements.txt
        sed -i 's/\"package\"/\"image\"/' ./config.json
    - name: Checkout pages
      run: |
        git fetch origin gh-pages
        git worktree add ./dist gh-pages
    - name: Force update
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        rm ./dist/process.json
    - name: Run
      run: |
        python -m index
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.PA_TOKEN }}
        branch: gh-pages
        folder: ./dist