name: CI

on:
  push:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
    - name: Prepare env
      run: |
        python -m pip install -r ./requirements.txt
        sed -i 's/\"package\"/\"image\"/' ./config.json
    - name: Run
      run: |
        python -m index
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4