name: CI

on:
  push:

defaults:
  run:
    shell: pwsh

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install -r ./requirements
    - name: Run
      run: |
        python -m index
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist